# Generated by Django 5.2.16 on 2026-08-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_matchanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchanalysis',
            name='model_used',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='matchanalysis',
            name='race_note',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
